### ISSUE TITLE
scater-pca-filter.R requires mvoutlier

### ISSUE THREAD

**Issue by nsoranzo** [ethering/scater_1.8.4_wrappers#2]
After following the installation instructions, I encountered the following issue while trying the `Typical workflow` from `README.md`:
```
$ ./scater-pca-filter.R -i test-data/scater_qcready_sce.rds -o test-data/scater_filtered.rds
[1] "Starting with 40 cells and 2000 features."
Error in loadNamespace(name) : there is no package called ‘mvoutlier’
Calls: runPCA ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

By looking at https://www.bioconductor.org/packages/release/bioc/html/scater.html , `mvoutlier` is among the `Suggests` packages for `scater`.

Also, in the [runPCA() source code](https://github.com/davismcc/scater/blob/master/R/runPCA.R#L114), you can notice that the `mvoutlier` package in not loaded (you may want to submit an issue there), so I'd propose to:
- add `mvoutlier` to the `install.packages()` command in the installation instructions
- load the `mvoutlier` package in `scater-pca-filter.R`

All the other examples ran fine.

**Comment by ethering** [comment]
Handled under commit 9676d2640559b948fc366c2b89a65b8d584ae304
Thanks.
Graham
